stages:
- name: mvn
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-samplejava:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34499
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification:
  recipients:
  - recipient: ashima.aggarwal@india.nec.com
    notifier: c-h8ztd:n-z8kdh
  condition:
  - Success
  - Changed
  - Failed
